[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
macros = "src/katex/macros.txt"

[output]

[output.katex]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
