name: Build and deploy mdbook to github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MDBOOK_VERSION: 0.4.18
  MERMAID_VERSION: 0.11.0
  KATEX_VERSION: 0.2.10
  MDBOOK_LINKCHECK_VER: 0.7.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Install mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: ${{env.MDBOOK_VERSION}}

    - name: Make binaries path
      run: |
        mkdir $HOME/bin
        echo $HOME/bin >> $GITHUB_PATH

    - name: Install mdbook-linkcheck
      run: | # `-L` because GitHub performs a redirection
        curl -L -o mdbook-linkcheck.zip "https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v${MDBOOK_LINKCHECK_VER}/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip"
        unzip mdbook-linkcheck.zip mdbook-linkcheck
        chmod +x mdbook-linkcheck
        cp mdbook-linkcheck $HOME/bin/

    - name: Install mdbook-mermaid
      run: |
        curl -L -o mdbook-mermaid.tar.gz "https://github.com/badboy/mdbook-mermaid/releases/download/v${MERMAID_VERSION}/mdbook-mermaid-v${MERMAID_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        tar -xf mdbook-mermaid.tar.gz
        chmod +x mdbook-mermaid
        cp mdbook-mermaid $HOME/bin/

    - name: Install mdbook-katex
      run: |
        curl -L -o mdbook-katex.tar.gz "https://github.com/lzanini/mdbook-katex/releases/download/v${KATEX_VERSION}/mdbook-katex-v${KATEX_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        tar -xf mdbook-katex.tar.gz
        cp ./target/x86_64-unknown-linux-gnu/release/mdbook-katex $HOME/bin/
        chmod +x $HOME/bin/mdbook-katex

    - name: Build
      env:
        MDBOOK_BUILD__CREATE_MISSING: "false" # Prevent creating missing files in SUMMARY.md
      run: |
        mdbook build

    - name: Store final build
      uses: actions/upload-artifact@v2
      with:
        name: Build output
        path: book
        if-no-files-found: error

    - name: Deploy to GitHub Pages 🚀
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book
