name: Build and deploy mdbook to github pages

on:
  push:

env:
  MDBOOK_VERSION: 0.4.18
  MERMAID_VERSION: 0.11.0
  KATEX_VERSION: 0.2.10
  MDBOOK_LINKCHECK_VER: 0.7.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout elv-spec
      uses: actions/checkout@v2
      with:
        path: elv-spec

    - name: Install mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: ${MDBOOK_VERSION}

    - name: Install mdbook-linkcheck
      run: | # `-L` because GitHub performs a redirection
        curl -L -o mdbook-linkcheck.zip "https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v${MDBOOK_LINKCHECK_VER}/mdbook-linkcheck.x86_64-unknown-linux-gnu.zip"
        unzip mdbook-linkcheck.zip mdbook-linkcheck
        chmod +x mdbook-linkcheck
    - name: Install mdbook-mermaid
      run: |
        curl -L -o mdbook-mermaid.zip "https://github.com/badboy/mdbook-mermaid/releases/download/v${MERMAID_VERSION}/mdbook-mermaid-v${MERMAID_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        unzip mdbook-mermaid.zip mdbook-mermaid
        chmod +x mdbook-mermaid
    - name: Install mdbook-katex
      run: |
        curl -L -o mdbook-katex.zip "https://github.com/lzanini/mdbook-katex/releases/download/v${KATEX_VERSION}/mdbook-katex-v${KATEX_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        unzip mdbook-katex.zip mdbook-katex
        chmod +x mdbook-katex
    - name: Build
      working-directory: elv-spec/
      env:
        MDBOOK_BUILD__CREATE_MISSING: "false" # Prevent creating missing files in SUMMARY.md
        MDBOOK_OUTPUT__LINKCHECK__COMMAND: "../mdbook-linkcheck"
      run: |
        mdbook build
    - name: Store final build
      uses: actions/upload-artifact@v2
      with:
        name: Build output
        path: elv-spec/docs/elv-spec/
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Do not run this unless *pushing* to `master`
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Checkout elv-spec/gh-pages
      uses: actions/checkout@v2
      with:
        path: elv-spec 
        ref: gh-pages

    - name: Delete all current files
      run: |
        rm -vrf elv-spec/*
    - name: Unpack build
      uses: actions/download-artifact@v2
      with:
        name: Build output
        path: elv-spec/

    - name: Deploy
      working-directory: elv-spec/
      run: |
        git config --local user.name "GitHub Action"
        git config --global user.email "william.arnold@eluv.io"
        git remote -v
        git branch -v
        git add -A
        git commit -am 'Update build'
        git push -v

